//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAdapter.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEI_TBL_TECH_DIVISION_MAST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IEI_TBL_TECH_DIVISION_MAST()
        {
            this.IEI_TBL_TECH_PROPOSAL = new HashSet<IEI_TBL_TECH_PROPOSAL>();
        }
    
        public string DIV { get; set; }
        public string DISCRIPTION { get; set; }
        public string CL { get; set; }
        public string REMARKS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IEI_TBL_TECH_PROPOSAL> IEI_TBL_TECH_PROPOSAL { get; set; }
    }
}
