//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAdapter.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEI_TBL_FILE_TYPES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IEI_TBL_FILE_TYPES()
        {
            this.IEI_TBL_FILE_UPLOADED = new HashSet<IEI_TBL_FILE_UPLOADED>();
        }
    
        public int FM_ID { get; set; }
        public string UPLOAD_DESC { get; set; }
        public string FILE_EXT { get; set; }
        public string FILE_MAX_SIZE { get; set; }
        public Nullable<int> NO_OF_FILES { get; set; }
        public string ROOT_PATH { get; set; }
        public string REMARKS { get; set; }
        public string CL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IEI_TBL_FILE_UPLOADED> IEI_TBL_FILE_UPLOADED { get; set; }
    }
}
