//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAdapter.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEI_TBL_CENTMAST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IEI_TBL_CENTMAST()
        {
            this.IEI_TBL_FRTH_EVENT = new HashSet<IEI_TBL_FRTH_EVENT>();
            this.IEI_TBL_TECH_PROPOSAL = new HashSet<IEI_TBL_TECH_PROPOSAL>();
        }
    
        public string CCODE { get; set; }
        public string TYPE { get; set; }
        public string CNAME { get; set; }
        public string CADL2 { get; set; }
        public string CADL3 { get; set; }
        public string CADL4 { get; set; }
        public string CADL5 { get; set; }
        public string EMAILID { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string COUNTRY_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IEI_TBL_FRTH_EVENT> IEI_TBL_FRTH_EVENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IEI_TBL_TECH_PROPOSAL> IEI_TBL_TECH_PROPOSAL { get; set; }
    }
}
