//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAdapter.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEI_TBL_TECH_PROPOSAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IEI_TBL_TECH_PROPOSAL()
        {
            this.IEI_TBL_FRTH_EVENT = new HashSet<IEI_TBL_FRTH_EVENT>();
            this.IEI_TBL_TECH_ASSOCIATE = new HashSet<IEI_TBL_TECH_ASSOCIATE>();
            this.IEI_TBL_TECH_SCHEDULE = new HashSet<IEI_TBL_TECH_SCHEDULE>();
        }
    
        public int TECH_PROP_ID { get; set; }
        public Nullable<int> REG_ID { get; set; }
        public string CCODE { get; set; }
        public Nullable<int> PROG_HD_ID { get; set; }
        public string DIVISION_BOARD { get; set; }
        public string PROG_TITLE { get; set; }
        public Nullable<bool> PROG_DT_VIOLATION_FLG { get; set; }
        public string DT_VIOLATION_RESION { get; set; }
        public Nullable<System.DateTime> PROG_DT { get; set; }
        public Nullable<int> NO_OF_DAYS { get; set; }
        public string PROG_VENUE { get; set; }
        public string CURR_AMT { get; set; }
        public Nullable<decimal> REQUEST_AMT { get; set; }
        public Nullable<decimal> GRANT_AMT { get; set; }
        public string PROG_ABSTRUCT { get; set; }
        public string PROP_IP_ADD { get; set; }
        public string PROPOSAL_FLAG { get; set; }
        public string PROPOSAL_STATUS { get; set; }
        public string REMARKS { get; set; }
        public string REPORT_STATUS { get; set; }
        public string REPORT_DESC { get; set; }
        public string REPORT_DETAILS_DESC_PATH { get; set; }
        public Nullable<int> DESC_FU_ID { get; set; }
        public string REPORT_IMG_DAIS_CAPTION { get; set; }
        public string REPORT_IMG_DAIS_PATH { get; set; }
        public Nullable<int> DAIS_FU_ID { get; set; }
        public string REPORT_IMG_TITLE_CAPTION { get; set; }
        public string REPORT_IMG_TITLE_PATH { get; set; }
        public Nullable<int> IMG_FU_ID { get; set; }
        public Nullable<System.DateTime> PROPOSAL_CREATE_DT { get; set; }
        public Nullable<System.DateTime> PROPOSAL_APPROVED_DT { get; set; }
        public Nullable<System.DateTime> PROPOSAL_REPORT_SUBMIT_DT { get; set; }
        public Nullable<int> USER_PROPOSAL_LOGIN { get; set; }
        public string USER_MODERATOR { get; set; }
        public string USER_MODERATOR_IP_ADD { get; set; }
        public Nullable<int> USER_REPORT_LOGIN { get; set; }
        public Nullable<int> INSERTED_ID { get; set; }
    
        public virtual IEI_TBL_FILE_UPLOADED IEI_TBL_FILE_UPLOADED { get; set; }
        public virtual IEI_TBL_FILE_UPLOADED IEI_TBL_FILE_UPLOADED1 { get; set; }
        public virtual IEI_TBL_FILE_UPLOADED IEI_TBL_FILE_UPLOADED2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IEI_TBL_FRTH_EVENT> IEI_TBL_FRTH_EVENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IEI_TBL_TECH_ASSOCIATE> IEI_TBL_TECH_ASSOCIATE { get; set; }
        public virtual IEI_TBL_TECH_DIVISION_MAST IEI_TBL_TECH_DIVISION_MAST { get; set; }
        public virtual IEI_TBL_TECH_PROG_HD IEI_TBL_TECH_PROG_HD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IEI_TBL_TECH_SCHEDULE> IEI_TBL_TECH_SCHEDULE { get; set; }
        public virtual IEI_TBL_CENTMAST IEI_TBL_CENTMAST { get; set; }
    }
}
